export const GET_CREATED_LISTS = "GET_CREATED_LISTS";
export const GET_CREATED_CARDS = "GET_CREATED_CARDS";

export const UPDATE_CARD_LIST = "UPDATE_CARD_LIST";
export const TOGGLE_NEW_CARD_FORM = "TOGGLE_NEW_CARD_FORM";