export const GET_CREATED_LISTS = "GET_CREATED_LISTS";
export const GET_CREATED_CARDS = "GET_CREATED_CARDS";

// CARD
export const NEW_CARD_TITLE = "NEW_CARD_TITLE";
export const ADD_NEW_CARD = "ADD_NEW_CARD";

// LIST
export const TOGGLE_NEW_CARD_FORM = "TOGGLE_NEW_CARD_FORM";
export const UPDATE_CARD_LIST = "UPDATE_CARD_LIST";